# Introduction

- Go handles errors by returning a value of type `error` as the last return value for a function. 
- When a function executes as expected, `nil` is returned for the error parameter. 
- If something goes wrong, an error value is returned instead. 
- The calling function then checks the error return value by comparing it to `nil`, handling the error or returning and error of its own.

```go
package main

import (
	"errors"
	"fmt"
	"os"
)

func calcRemainderAndMode(numerator, denominator int) (int, int, error) {
	if denominator == 0 {
		return 0, 0, errors.New("denominator is 0")
	}
	return numerator / denominator, numerator % denominator, nil
}

func main() {
	numerator := 20
	denominator := 3
	remainder, mod, err := calcRemainderAndMode(numerator, denominator)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Println(remainder, mod)
}
```

```sh
chan@CMA:~/Go_Programming/ch1$ make
go fmt ./...
hello.go
go vet ./...
go build
chan@CMA:~/Go_Programming/ch1$ ./hello_world
6 2
```

