# Wrapping Multiple Errors

- Sometimes a function generates multiple errors that should be returned.

  - E.g, if we write a function to validate the fields in a struct, it would be better to return an error for each invalid field.
  - Since the standard function signature returns `error` and not `[]error`, we need to merge multiple errors into a single error.
  - That's what the `errors.Join` function is for.
  - Another way to merge multiple errors is to pass multiple `%w` to `fmt.Errorf`

  ```go
  err1 := errors.New("first error")
  err2 := errors.New("second error")
  err3 := errors.New("third error")
  err := fmt.Errorf("first: %w, second: %w, third: %w", err1, err2, err3)
  ```

  

---

## Code Example #1 (Using `errors.Join`)

```go
package main

import (
	"errors"
	"fmt"
)

type Person struct {
	FirstName string
	LastName  string
	Age       int
}

func ValidatePerson(p Person) error {
	var errs []error
	if len(p.FirstName) == 0 {
		errs = append(errs, errors.New("field FirstName cannot be empty"))
	}
	if len(p.LastName) == 0 {
		errs = append(errs, errors.New("field LastName cannot be empty"))
	}
	if p.Age < 0 || p.Age > 120 || p.Age == 0 || p.Age < 16 {
		errs = append(errs, errors.New("invalid age, must be between 16 and 120"))
	}
	if len(errs) > 0 {
		return errors.Join(errs...)
	}
	return nil
}

func main() {
	p := Person{
		FirstName: "",
		LastName:  "Aung",
		Age:       0,
	}

	err := ValidatePerson(p)
	if err != nil {
		fmt.Println("Validation errors:")
		fmt.Println(err.Error())
	} else {
		fmt.Println("Person is valid")
	}
}
```

```sh
chan@CMA:~/Go_Programming/ch1$ make
go fmt ./...
go vet ./...
go build
chan@CMA:~/Go_Programming/ch1$ ./hello_world
Validation errors:
field FirstName cannot be empty
invalid age, must be between 16 and 120
```

---

## Code Example #2

```go
package main

import (
	"errors"
	"fmt"
)

type MyError struct {
	Code   int
	Errors []error
}

func (m MyError) Error() string {
	return errors.Join(m.Errors...).Error()
}

func (m MyError) Unwrap() []error {
	return m.Errors
}

type Person struct {
	FirstName string
	LastName  string
	Age       int
}

func ValidatePerson(p Person) error {
	var errs []error
	if len(p.FirstName) == 0 {
		errs = append(errs, errors.New("field FirstName cannot be empty"))
	}
	if len(p.LastName) == 0 {
		errs = append(errs, errors.New("field LastName cannot be empty"))
	}
	if p.Age < 0 || p.Age > 120 || p.Age == 0 || p.Age < 16 {
		errs = append(errs, errors.New("invalid age, must be between 16 and 120"))
	}
	if len(errs) > 0 {
		return MyError{
			Code:   404,
			Errors: errs,
		}
	}
	return nil
}

func main() {
	p := Person{
		FirstName: "",
		LastName:  "Aung",
		Age:       0,
	}

	err := ValidatePerson(p)
	if err == nil {
		fmt.Println("Person is valid")
		return
	}

	// error.As lets us look thru a chain of wrapped errors and see if any one of them is of a specific concrete type
	var me MyError
	if errors.As(err, &me) {
		fmt.Printf("Validation failed with code %d: \n", me.Code)
		for i, e := range me.Errors {
			fmt.Printf(" %d) %s\n", i+1, e)
		}
	} else {
		// fallback for any other error
		fmt.Println("error:", err)
	}
}
```

```sh
chan@CMA:~/Go_Programming/ch1$ make
go fmt ./...
hello.go
go vet ./...
go build
chan@CMA:~/Go_Programming/ch1$ ./hello_world
Validation failed with code 404: 
 1) field FirstName cannot be empty
 2) invalid age, must be between 16 and 120
```

---

